Repository zheedong/Ani2Pok, pull requests merged in 2023-02, with the labels that each got.

#3 Donghwan adds images and type table
  data/images/.DS_Store
  data/images/[Warning] butterfly.jpg
  data/images/[Warning] ladybug.jpg
  data/images/animal type data.csv
  data/images/bear.jpg
  data/images/chimpanzee.jpg
  data/images/crab.jpg
  data/images/deer.jpg
  data/images/duck.jpg
  data/images/eagle.jpg
  data/images/flamingo.jpg
  data/images/fox.jpg
  data/images/horse.jpg
  data/images/orca.jpg
  data/images/panda.jpg
  data/images/penguin.jpg
  data/images/shark.jpg
Labels: Dataset

#4 Feat: Add images and type data table
  data/images/Adélie penguin.jfif
  data/images/Eurasian lynx.jfif
  data/images/Long-tailed tit.jfif
  data/images/Northern goshawk.jfif
  data/images/[WARNING] snake.jfif
  data/images/[WARNING] stag beetle.jfif
  data/images/animal type data.csv
  data/images/baby emperor penguin.jfif
  data/images/chicken.jfif
  data/images/crow.jfif
  data/images/flying squirrel.png
  data/images/giraffe.jfif
  data/images/goldfish.jfif
  data/images/gorilla.jfif
  data/images/octopus.jfif
  data/images/snail.jfif
  data/images/wolf.jfif
Labels: Dataset

#5 added new dataset
  .DS_Store
  data/.DS_Store
  data/images/[WARNING] bee.jpg
  data/images/animal type data.csv
  data/images/antelope.jpg
  data/images/badger.jpg
  data/images/bat.jpg
  data/images/boar.jpg
  data/images/cat.jpg
  data/images/dog.jpg
  data/images/dolphin.jpg
  data/images/goat.jpg
  data/images/hamster.jpg
  data/images/hedgehog.jpg
  data/images/koala.jpg
  data/images/leopard.jpg
  data/images/raccoon.jpg
  data/images/zebra.jpg
Labels: Dataset

#8 Magic mix - .DS_Store deleted
  .gitignore
  README.md
  data/images/.DS_Store
  gradio.py
  models/magicmix/.env.example
  models/magicmix/.gitignore
  models/magicmix/README.md
  models/magicmix/contents/image_text_mix_csp_coffee machine_mixed_nu:0.8_0.png
  models/magicmix/contents/image_text_mix_csp_tiger_mixed_nu:0.8_1.png
  models/magicmix/contents/lp_a realistic photo of a cat_csp_coffee machine_mixed_nu:0.75_0.png
  models/magicmix/contents/lp_a realistic photo of a cat_csp_coffee machine_mixed_nu:0.9_0.png
  models/magicmix/contents/lp_a realistic photo of a cat_csp_coffee machine_original_0.png
  models/magicmix/contents/lp_a realistic photo of a rabbit_csp_tiger_mixed_nu:0.75_1.png
  models/magicmix/contents/lp_a realistic photo of a rabbit_csp_tiger_mixed_nu:0.9_1.png
  models/magicmix/contents/lp_a realistic photo of a rabbit_csp_tiger_original_1.png
  models/magicmix/contents/magicmix.png
  models/magicmix/contents/test.jpg
  models/magicmix/contents/test_cat.jpg
  models/magicmix/magic_mix/magic_mix.py
  models/magicmix/requirements.txt
  models/magicmix/scripts/run_sample_and_mix.py
  models/magicmix/scripts/run_text_image_mix.py
  models/magicmix/setup.py
  models/magicmix_colab/.DS_Store
Labels: model

#11 rembg 추가 -> 2-stage 모델로 만듦 + readme 수정
  README.md
  data/images/Adélie penguin.jpg
  data/images/Eurasian lynx.jpg
  data/images/Long-tailed tit.jpg
  data/images/Northern goshawk.jpg
  data/images/[WARNING] snake.jpg
  data/images/[WARNING] stag beetle.jpg
  data/images/chicken.jpg
  data/images/giraffe.jpg
  data/images/goldfish.jpg
  data/images/gorilla.jpg
  gradio.py
  models/rembg_colab/Rembg+MagicMix.ipynb
Labels: documentation, model
